variables:
    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip
    - .venv

stages:
  - quality
  - tests

.quality-template: &quality
  image: python:3.6
  stage: quality

check-black:
  <<: *quality
  before_script:
    - pip install black
  script: black --check src/ tests/

check-isort:
  <<: *quality
  before_script:
    - pip install isort[pyproject]
  script: isort -c -rc src/ tests/

check-flake8:
  <<: *quality
  before_script:
    - pip install flake8
  script: flake8 src/ tests/

check-bandit:
  <<: *quality
  before_script:
    - pip install bandit
  script: bandit -r src/

check-safety:
  <<: *quality
  before_script:
    - apt-get update
    - apt-get install -y python-enchant
    - pip install poetry
    - poetry config settings.virtualenvs.in-project true
    - poetry install -vv
    - poetry --version
  script: make check-safety

.test-template: &test
  stage: tests
  before_script:
    - apt-get update
    - apt-get install -y python-enchant
    - apt-get install -y aria2
    - pip install poetry
    - poetry config settings.virtualenvs.in-project true
    - poetry install -vv
    - poetry --version
  script: poetry run pytest -v

python3.6:
  <<: *test
  image: python:3.6

python3.7:
  <<: *test
  image: python:3.7

python3.8:
  <<: *test
  image: python:3.8-rc
  allow_failure: true

